幹事一覧を更新
wakate/wakate.github.io pull request #192
Opened 2023-09-02 15:16 UTC by kyontan

2023-09-02 16:02 UTC, ishitatsuyuki requested changes
黒崎さんの幹事からの削除については了解です。

2023-09-02 16:02 UTC, ishitatsuyuki commented on source/posts/2023-08-04-56th-general.html.md
> -情報科学若手の会とは、情報科学に携わる学生、若手研究者、社会人のディスカッションと交流の会です（[昨年の開催報告](https://wakate.org/2022/11/09/55threport/)）。
Markdown の改行用スペースが抜かれてるので、それが抜かれないようにエディタの設定をお願いします。

2023-09-02 17:25 UTC, kyontan commented on source/posts/2023-08-04-56th-general.html.md
> -情報科学若手の会とは、情報科学に携わる学生、若手研究者、社会人のディスカッションと交流の会です（[昨年の開催報告](https://wakate.org/2022/11/09/55threport/)）。
@ishitatsuyuki すみません見落としていました 🙇  修正しました

2023-09-02 17:26 UTC, ishitatsuyuki approved these changes

2023-09-03 11:57 UTC, musaprg approved these changes

2023-09-03 11:57 UTC, mt-caret approved these changes

2023-09-03 11:57 UTC, merged