現時点で確定している発表を追加
wakate/wakate.github.io pull request #193
Opened 2023-09-18 16:34 UTC by mt-caret

2023-09-18 17:05 UTC, musaprg commented on source/posts/2023-08-04-56th-general.html.md
> +* 松本直京 (都大学)
```suggestion
* 松本直京 (京都大学)
```

2023-09-18 17:06 UTC, mt-caret commented on source/posts/2023-08-04-56th-general.html.md
> +* 松本直京 (都大学)
🤦
指摘ありがとうございます...

2023-09-18 17:33 UTC, ishitatsuyuki approved these changes

2023-09-19 09:57 UTC, naoki9911 requested changes

2023-09-19 09:57 UTC, naoki9911 commented on source/posts/2023-08-04-56th-general.html.md
> +* 松本直京 (京都大学)
typo です
松本直樹 でお願いします

2023-09-19 11:10 UTC, astpy commented
（やべ。TBDのままじゃん）

2023-09-19 11:13 UTC, astpy commented
TBDだとあれなので私の分は一旦消しておいてもらえますか

2023-09-19 14:44 UTC, mt-caret commented on source/posts/2023-08-04-56th-general.html.md
> +* 松本直京 (京都大学)
ごめんなさい...vimで色々編集していたら所属と名前の間が消えていました...

2023-09-19 14:50 UTC, astpy approved these changes

2023-09-19 16:43 UTC, naoki9911 approved these changes

2023-09-19 16:43 UTC, naoki9911 commented on source/posts/2023-08-04-56th-general.html.md
> +* 上田蒼一朗 (京都大学工学部情報学科)
お二人で発表とのことなので、
上田蒼一朗 (京都大学工学部情報学科), 野崎愛 (東京大学情報理工学系研究科)
にした方がいいかもです。

2023-09-19 16:47 UTC, mt-caret commented on source/posts/2023-08-04-56th-general.html.md
> +* 上田蒼一朗 (京都大学工学部情報学科)
done

2023-09-19 16:48 UTC, merged